/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_leonardoborjas;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Borjas
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdCrearPaciente = new javax.swing.JDialog();
        rbS2 = new javax.swing.JRadioButton();
        rbN3 = new javax.swing.JRadioButton();
        rbM1 = new javax.swing.JRadioButton();
        rbF1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jsEdad1 = new javax.swing.JSpinner();
        tfSangre1 = new javax.swing.JTextField();
        tfNombre1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfFI1 = new javax.swing.JTextField();
        tfId1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfFA1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jsAltura1 = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        tfCausa1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        rbS1 = new javax.swing.JRadioButton();
        rbN4 = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jsPeso1 = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        cborganos = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        color = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jsPotenciado = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jsPrueba = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jbagregar = new javax.swing.JButton();
        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        bg3 = new javax.swing.ButtonGroup();
        jdCrearDoctor = new javax.swing.JDialog();
        jLabel35 = new javax.swing.JLabel();
        jsAltura2 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        rbM2 = new javax.swing.JRadioButton();
        rbF2 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jsEdad2 = new javax.swing.JSpinner();
        tfNombre2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        tfId2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jsPeso2 = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tdoctor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        horario1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horario2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lunes = new javax.swing.JCheckBox();
        martes = new javax.swing.JCheckBox();
        miercoles = new javax.swing.JCheckBox();
        jueves = new javax.swing.JCheckBox();
        viernes = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        domingo = new javax.swing.JCheckBox();
        jdModP = new javax.swing.JDialog();
        cbmodP = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tfFA2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jsAltura3 = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        tfCausa2 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        rbS3 = new javax.swing.JRadioButton();
        rbS4 = new javax.swing.JRadioButton();
        rbN5 = new javax.swing.JRadioButton();
        rbN6 = new javax.swing.JRadioButton();
        rbM3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rbF3 = new javax.swing.JRadioButton();
        jsPotenciado1 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jsPrueba1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jsEdad3 = new javax.swing.JSpinner();
        tfSangre2 = new javax.swing.JTextField();
        tfNombre3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        tfFI2 = new javax.swing.JTextField();
        tfId3 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jsPeso3 = new javax.swing.JSpinner();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        cborganos1 = new javax.swing.JComboBox<>();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        color1 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        cbo = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jdElimP = new javax.swing.JDialog();
        cbmodP1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        p = new javax.swing.JButton();

        bg3.add(rbS2);
        rbS2.setText("Si");

        bg3.add(rbN3);
        rbN3.setText("No");

        bg1.add(rbM1);
        rbM1.setText("M");

        bg1.add(rbF1);
        rbF1.setText("F");

        jButton3.setText("Crear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setText("Edad");

        jLabel19.setText("Tipo de Sangre");

        jLabel20.setText("Fecha de Ingreso");

        jLabel21.setText("Nombre");

        jLabel22.setText("Fecha de Alta");

        jLabel23.setText("ID");

        jLabel24.setText("Altura");

        jsAltura1.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.0d, null, 0.1d));

        jLabel25.setText("Causa de la visita");

        jLabel26.setText("Marque Si o No en las siguientes si contiene una o mas:");

        bg2.add(rbS1);
        rbS1.setText("Si");
        rbS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS1ActionPerformed(evt);
            }
        });

        bg2.add(rbN4);
        rbN4.setText("No");

        jLabel27.setText("Peso");

        jsPeso1.setModel(new javax.swing.SpinnerNumberModel(0.1d, null, null, 0.1d));

        jLabel28.setText("Sexo");

        jLabel29.setText("Alergias?");

        jLabel30.setText("Enfermedades?");

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setText("Agregar Organo");

        cborganos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estomago", "Hígado", "Cerebro", "Páncreas", "Corazón", "Pulmones", "Riñones" }));

        jLabel32.setText("Organo");

        jLabel33.setText("Color");

        color.setBackground(new java.awt.Color(255, 51, 51));
        color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorMouseClicked(evt);
            }
        });
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setText("Creacion de Paciente");

        jLabel1.setText("Potenciado");

        jLabel2.setText("Prueba");

        jLabel3.setText("Niveles:");

        jbagregar.setText("Agregar");
        jbagregar.setEnabled(false);
        jbagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdCrearPacienteLayout = new javax.swing.GroupLayout(jdCrearPaciente.getContentPane());
        jdCrearPaciente.getContentPane().setLayout(jdCrearPacienteLayout);
        jdCrearPacienteLayout.setHorizontalGroup(
            jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel31)
                            .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfFA1)
                                    .addComponent(tfCausa1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfFI1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                    .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel28))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                            .addComponent(rbM1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbF1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfSangre1))
                                        .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                            .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfId1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jsEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jsAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                                    .addComponent(jLabel27)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jsPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jLabel26)
                            .addComponent(jLabel34)
                            .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdCrearPacienteLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jsPotenciado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jsPrueba))
                                .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                    .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel32)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cborganos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(11, 11, 11)
                                            .addComponent(jLabel33))
                                        .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                            .addGap(0, 41, Short.MAX_VALUE)
                                            .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                                    .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                                            .addComponent(rbS1)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(rbN4))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdCrearPacienteLayout.createSequentialGroup()
                                                            .addComponent(rbS2)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(rbN3))))
                                                .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                                                    .addComponent(jButton3)
                                                    .addGap(53, 53, 53)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jdCrearPacienteLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jbagregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdCrearPacienteLayout.setVerticalGroup(
            jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdCrearPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jsEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24)
                    .addComponent(jsAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel27)
                    .addComponent(jsPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbM1)
                    .addComponent(rbF1)
                    .addComponent(jLabel19)
                    .addComponent(tfSangre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfFI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfFA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tfCausa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(rbS1)
                    .addComponent(rbN4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(rbS2)
                    .addComponent(rbN3))
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cborganos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel33))
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(jdCrearPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jsPotenciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jsPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbagregar)
                .addContainerGap())
        );

        jLabel35.setText("Altura");

        jsAltura2.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.0d, null, 0.1d));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel36.setText("Creacion de Doctor");

        bg1.add(rbM2);
        rbM2.setText("M");

        bg1.add(rbF2);
        rbF2.setText("F");

        jLabel37.setText("Edad");

        jLabel38.setText("Nombre");

        jLabel39.setText("Peso");

        jsPeso2.setModel(new javax.swing.SpinnerNumberModel(0.1d, null, null, 0.1d));

        jLabel40.setText("Sexo");

        jLabel5.setText("Tiempo como doctor");

        jLabel6.setText("Horario");

        jLabel7.setText("pm    a");

        jLabel8.setText("pm");

        jButton8.setText("Crear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel9.setText("ID");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dias de Trabajo"));

        lunes.setText("lunes");

        martes.setText("martes");

        miercoles.setText("miercoles");

        jueves.setText("jueves");

        viernes.setText("viernes");

        sabado.setText("sabado");

        domingo.setText("domingo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lunes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(martes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(miercoles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jueves))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(viernes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sabado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domingo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunes)
                    .addComponent(martes)
                    .addComponent(miercoles)
                    .addComponent(jueves))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viernes)
                    .addComponent(sabado)
                    .addComponent(domingo))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdCrearDoctorLayout = new javax.swing.GroupLayout(jdCrearDoctor.getContentPane());
        jdCrearDoctor.getContentPane().setLayout(jdCrearDoctorLayout);
        jdCrearDoctorLayout.setHorizontalGroup(
            jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                        .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                        .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel38)
                                            .addComponent(jLabel40)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tfId2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                                        .addComponent(jLabel37)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jsEdad2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                                        .addComponent(jLabel35)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jsAltura2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                                        .addComponent(jLabel39)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jsPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                                .addComponent(rbM2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbF2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tdoctor))))
                                    .addComponent(jLabel36)))
                            .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horario1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(horario2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdCrearDoctorLayout.setVerticalGroup(
            jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCrearDoctorLayout.createSequentialGroup()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jsEdad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel35)
                    .addComponent(jsAltura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel39)
                        .addComponent(jsPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbM2)
                    .addComponent(rbF2)
                    .addComponent(jLabel40)
                    .addComponent(jLabel5)
                    .addComponent(tdoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdCrearDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(horario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(horario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jLabel10.setText("Paciente");

        jLabel41.setText("Fecha de Alta");

        jLabel42.setText("ID");

        jLabel43.setText("Altura");

        jsAltura3.setModel(new javax.swing.SpinnerNumberModel(0.1d, 0.0d, null, 0.1d));

        jLabel44.setText("Causa de la visita");

        jLabel45.setText("Marque Si o No en las siguientes si contiene una o mas:");

        bg3.add(rbS3);
        rbS3.setSelected(true);
        rbS3.setText("Si");

        bg2.add(rbS4);
        rbS4.setSelected(true);
        rbS4.setText("Si");
        rbS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS4ActionPerformed(evt);
            }
        });

        bg3.add(rbN5);
        rbN5.setText("No");

        bg2.add(rbN6);
        rbN6.setText("No");

        bg1.add(rbM3);
        rbM3.setSelected(true);
        rbM3.setText("M");

        jLabel11.setText("Potenciado");

        bg1.add(rbF3);
        rbF3.setText("F");

        jLabel12.setText("Prueba");

        jLabel13.setText("Niveles:");

        jButton9.setText("Crear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel46.setText("Edad");

        jLabel47.setText("Tipo de Sangre");

        jLabel48.setText("Fecha de Ingreso");

        jLabel49.setText("Nombre");

        jLabel50.setText("Peso");

        jsPeso3.setModel(new javax.swing.SpinnerNumberModel(0.1d, null, null, 0.1d));

        jLabel51.setText("Sexo");

        jLabel52.setText("Alergias?");

        jLabel53.setText("Enfermedades?");

        jLabel54.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel54.setText("Agregar Organo");

        cborganos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estomago", "Hígado", "Cerebro", "Páncreas", "Corazón", "Pulmones", "Riñones" }));

        jLabel55.setText("Organo");

        jLabel56.setText("Color");

        color1.setBackground(new java.awt.Color(255, 51, 51));
        color1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                color1MouseClicked(evt);
            }
        });
        color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color1ActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel57.setText("Modificar de Paciente");

        jLabel16.setText("Organo");

        javax.swing.GroupLayout jdModPLayout = new javax.swing.GroupLayout(jdModP.getContentPane());
        jdModP.getContentPane().setLayout(jdModPLayout);
        jdModPLayout.setHorizontalGroup(
            jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdModPLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbmodP, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdModPLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addComponent(jLabel54)
                        .addGroup(jdModPLayout.createSequentialGroup()
                            .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel48)
                                .addComponent(jLabel41)
                                .addComponent(jLabel44))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfFA2)
                                .addComponent(tfCausa2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfFI2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jdModPLayout.createSequentialGroup()
                                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel51))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jdModPLayout.createSequentialGroup()
                                        .addComponent(rbM3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbF3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfSangre2))
                                    .addGroup(jdModPLayout.createSequentialGroup()
                                        .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfId3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jdModPLayout.createSequentialGroup()
                                                .addComponent(jLabel46)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jsEdad3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jdModPLayout.createSequentialGroup()
                                                .addComponent(jLabel43)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jsAltura3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jdModPLayout.createSequentialGroup()
                                                .addComponent(jLabel50)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jsPeso3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addComponent(jLabel45)
                        .addComponent(jLabel57)
                        .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdModPLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsPotenciado1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsPrueba1))
                            .addGroup(jdModPLayout.createSequentialGroup()
                                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jdModPLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel55)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cborganos1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel56))
                                    .addGroup(jdModPLayout.createSequentialGroup()
                                        .addGap(0, 41, Short.MAX_VALUE)
                                        .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jdModPLayout.createSequentialGroup()
                                                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jdModPLayout.createSequentialGroup()
                                                        .addComponent(rbS4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rbN6))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jdModPLayout.createSequentialGroup()
                                                        .addComponent(rbS3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rbN5))))
                                            .addGroup(jdModPLayout.createSequentialGroup()
                                                .addComponent(jButton9)
                                                .addGap(53, 53, 53)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(color1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jdModPLayout.setVerticalGroup(
            jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdModPLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmodP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(129, 129, 129))
            .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jdModPLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabel57)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46)
                        .addComponent(jsEdad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49)
                        .addComponent(jLabel43)
                        .addComponent(jsAltura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42)
                        .addComponent(jLabel50)
                        .addComponent(jsPeso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbM3)
                        .addComponent(rbF3)
                        .addComponent(jLabel47)
                        .addComponent(tfSangre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel48)
                        .addComponent(tfFI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel41)
                        .addComponent(tfFA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(tfCausa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel45)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel52)
                        .addComponent(rbS4)
                        .addComponent(rbN6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel53)
                        .addComponent(rbS3)
                        .addComponent(rbN5))
                    .addGap(18, 18, 18)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(jLabel54)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cborganos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56))
                        .addComponent(color1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel13)
                    .addGap(14, 14, 14)
                    .addGroup(jdModPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jsPotenciado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jsPrueba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(11, 11, 11)))
        );

        jLabel14.setText("Paciente");

        jLabel15.setText("Eliminar Paciente");

        jButton10.setText("Eliminar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdElimPLayout = new javax.swing.GroupLayout(jdElimP.getContentPane());
        jdElimP.getContentPane().setLayout(jdElimPLayout);
        jdElimPLayout.setHorizontalGroup(
            jdElimPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdElimPLayout.createSequentialGroup()
                .addGroup(jdElimPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdElimPLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jdElimPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jdElimPLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbmodP1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jdElimPLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton10)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jdElimPLayout.setVerticalGroup(
            jdElimPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdElimPLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jdElimPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmodP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jButton10)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Menu");

        jButton1.setText("Modificar Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar Doctor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar Paciente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar Paciente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Modificar Doctor");

        jButton7.setText("Eliminar Doctor");

        p.setText("Pasar todo a Binario");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(p)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String sexo = "";
        if (rbM1.isSelected()) {
            sexo = "Masculino";
        } else {
            sexo = "Femenino";
        }
        Paciente p = new Paciente(tfFI1.getText(), tfFA1.getText(), tfSangre1.getText(), tfCausa1.getText(),
                tfNombre1.getText(), (Integer) jsEdad1.getValue(), Integer.parseInt(tfId1.getText()),
                (Double) jsAltura1.getValue(), (Double) jsPeso1.getValue(), sexo);
        if (rbS1.isSelected()) {
            String seguir = "s";
            while (seguir.equalsIgnoreCase("s")) {
                String alergia = JOptionPane.showInputDialog(this, "Cual Alergia?");
                p.getAlergias().add(alergia);
                seguir = JOptionPane.showInputDialog("Tiene otra alergia? s/n");
            }
        }
        if (rbS2.isSelected()) {
            String seguir = "s";
            while (seguir.equalsIgnoreCase("s")) {
                String enfermedad = JOptionPane.showInputDialog(this, "Cual Enfermedad?");
                p.getEnfermedades().add(enfermedad);
                seguir = JOptionPane.showInputDialog("Tiene otra Enfermedad? s/n");
            }
        }
        
        pacientes.add(p);
        JOptionPane.showMessageDialog(this, "Creado");
        jbagregar.setEnabled(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void rbS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS1ActionPerformed

    private void colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_colorMouseClicked

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
        color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow));
    }//GEN-LAST:event_colorActionPerformed

    private void jbagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagregarActionPerformed
        // TODO add your handling code here:

        if (jbagregar.isEnabled()) {
            String organo = (String) cborganos.getSelectedItem();
            int efectividad = 0;
            
            switch (organo) {
                case "Estomago":
                    efectividad = 52580;
                    break;
                case "Hígado":
                    efectividad = 69864;
                    break;
                case "Cerebro":
                    efectividad = 600000;
                case "Páncreas":
                    efectividad = 984236;
                case "Corazón":
                    efectividad = 21546;
                case "Pulmones":
                    efectividad = 589213;
                case "Riñones":
                    efectividad = 753266;
            }
            
            
            pacientes.get(pacientes.size()-1).getOrganos().add(new Organo(color.getBackground(), efectividad,
                            (Integer) jsPotenciado.getValue(), (Integer) jsPrueba.getValue()));
            String seguir = JOptionPane.showInputDialog("Desea agregar caracteristica? s/n");

            while (seguir.equalsIgnoreCase("s")) {
                String carac = JOptionPane.showInputDialog("Cual caracteristica quiere agregarle?");
                pacientes.get(pacientes.size()-1).getOrganos().get(pacientes.get(pacientes.size()-1).getOrganos().size()-1).getCaracteristicas().add(carac);
                seguir = JOptionPane.showInputDialog("Desea agregar otra caracteristica? s/n");
            }
            
        } else {

        }
    }//GEN-LAST:event_jbagregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cbmodP.setModel(new DefaultComboBoxModel());
        DefaultComboBoxModel m=(DefaultComboBoxModel)cbmodP.getModel();
        for (Paciente paciente : pacientes) {
            m.addElement(paciente);
        }
        cbmodP.setModel(m);
        
        cbo.setModel(new DefaultComboBoxModel());
        DefaultComboBoxModel p=(DefaultComboBoxModel)cbo.getModel();
        for (int i = 0; i < pacientes.size()-1; i++) {
            for (Organo o : pacientes.get(i).getOrganos()) {
                p.addElement(o);
            }
        }
        cbo.setModel(p);
        
        jdModP.setModal(true);
        jdModP.pack();
        jdModP.setLocationRelativeTo(this);
        jdModP.setVisible(true);
        cbmodP.setModel(new DefaultComboBoxModel());
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jdCrearDoctor.setModal(true);
        jdCrearDoctor.pack();
        jdCrearDoctor.setLocationRelativeTo(this);
        jdCrearPaciente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jdCrearPaciente.setModal(true);
        jdCrearPaciente.pack();
        jdCrearPaciente.setLocationRelativeTo(this);
        jdCrearPaciente.setVisible(true);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String sexo="";
        if (rbM2.isSelected()) {
            sexo="Masculino";
        }else{
            sexo="Femenino";
        }
        Doctor d = new Doctor(Integer.parseInt(tdoctor.getText()),horario1.getText()
                +" a "+horario2.getText(),tfNombre2.getText(),(Integer)jsEdad2.getValue(),
                Integer.parseInt(tfId2.getText()),(Double)jsAltura2.getValue(),(Double)jsPeso2.getValue(),sexo);
        doctores.add(d);
        
        if (lunes.isSelected()) {
            doctores.get(doctores.size()-1).getDias().add("Lunes");
        }
        if (martes.isSelected()) {
            doctores.get(doctores.size()-1).getDias().add("Martes");
        }
        if (miercoles.isSelected()) {
            doctores.get(doctores.size()-1).getDias().add("Miercoles");
        }
        if (jueves.isSelected()) {
            doctores.get(doctores.size()-1).getDias().add("Jueves");
        }
        if (viernes.isSelected()) {
            doctores.get(doctores.size()-1).getDias().add("Viernes");
        }
        if (sabado.isSelected()) {
            doctores.get(doctores.size()-1).getDias().add("Sabado");
        }
        if (domingo.isSelected()) {
            doctores.get(doctores.size()-1).getDias().add("Domingo");
        }
        JOptionPane.showMessageDialog(this, "Doctor creado");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void rbS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Paciente p=(Paciente)cbmodP.getSelectedItem();
        String sexo="";
        p.setNombre(tfNombre3.getText());
        p.setCausa(tfCausa2.getText());
        p.setEdad((Integer)jsEdad3.getValue());
        p.setAltura((Double)jsAltura3.getValue());
        p.setId(Integer.parseInt(tfId3.getText()));
        p.setDealta(tfFA2.getText());
        p.setFechaingreso(tfFI2.getText());
        if (rbM3.isSelected()) {
            sexo="Masculino";
        }else{
            sexo="Femenino";
        }
        p.setSexo(sexo);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void color1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_color1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_color1MouseClicked

    private void color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_color1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel m=(DefaultComboBoxModel)cbmodP1.getModel();
        for (Paciente paciente : pacientes) {
            m.addElement(paciente);
        }
        cbmodP1.setModel(m);
        
        jdElimP.setModal(true);
        jdElimP.pack();
        jdElimP.setLocationRelativeTo(this);
        jdElimP.setVisible(true);
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Paciente p=(Paciente)cbmodP1.getSelectedItem();
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.ButtonGroup bg3;
    private javax.swing.JComboBox<String> cbmodP;
    private javax.swing.JComboBox<String> cbmodP1;
    private javax.swing.JComboBox<String> cbo;
    private javax.swing.JComboBox<String> cborganos;
    private javax.swing.JComboBox<String> cborganos1;
    private javax.swing.JButton color;
    private javax.swing.JButton color1;
    private javax.swing.JCheckBox domingo;
    private javax.swing.JTextField horario1;
    private javax.swing.JTextField horario2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbagregar;
    private javax.swing.JDialog jdCrearDoctor;
    private javax.swing.JDialog jdCrearPaciente;
    private javax.swing.JDialog jdElimP;
    private javax.swing.JDialog jdModP;
    private javax.swing.JSpinner jsAltura1;
    private javax.swing.JSpinner jsAltura2;
    private javax.swing.JSpinner jsAltura3;
    private javax.swing.JSpinner jsEdad1;
    private javax.swing.JSpinner jsEdad2;
    private javax.swing.JSpinner jsEdad3;
    private javax.swing.JSpinner jsPeso1;
    private javax.swing.JSpinner jsPeso2;
    private javax.swing.JSpinner jsPeso3;
    private javax.swing.JSpinner jsPotenciado;
    private javax.swing.JSpinner jsPotenciado1;
    private javax.swing.JSpinner jsPrueba;
    private javax.swing.JSpinner jsPrueba1;
    private javax.swing.JCheckBox jueves;
    private javax.swing.JCheckBox lunes;
    private javax.swing.JCheckBox martes;
    private javax.swing.JCheckBox miercoles;
    private javax.swing.JButton p;
    private javax.swing.JRadioButton rbF1;
    private javax.swing.JRadioButton rbF2;
    private javax.swing.JRadioButton rbF3;
    private javax.swing.JRadioButton rbM1;
    private javax.swing.JRadioButton rbM2;
    private javax.swing.JRadioButton rbM3;
    private javax.swing.JRadioButton rbN3;
    private javax.swing.JRadioButton rbN4;
    private javax.swing.JRadioButton rbN5;
    private javax.swing.JRadioButton rbN6;
    private javax.swing.JRadioButton rbS1;
    private javax.swing.JRadioButton rbS2;
    private javax.swing.JRadioButton rbS3;
    private javax.swing.JRadioButton rbS4;
    private javax.swing.JCheckBox sabado;
    private javax.swing.JTextField tdoctor;
    private javax.swing.JTextField tfCausa1;
    private javax.swing.JTextField tfCausa2;
    private javax.swing.JTextField tfFA1;
    private javax.swing.JTextField tfFA2;
    private javax.swing.JTextField tfFI1;
    private javax.swing.JTextField tfFI2;
    private javax.swing.JTextField tfId1;
    private javax.swing.JTextField tfId2;
    private javax.swing.JTextField tfId3;
    private javax.swing.JTextField tfNombre1;
    private javax.swing.JTextField tfNombre2;
    private javax.swing.JTextField tfNombre3;
    private javax.swing.JTextField tfSangre1;
    private javax.swing.JTextField tfSangre2;
    private javax.swing.JCheckBox viernes;
    // End of variables declaration//GEN-END:variables

ArrayList<Paciente> pacientes=new ArrayList();
ArrayList<Doctor> doctores=new ArrayList();
Administrar ad=new Administrar("./Archivo",pacientes,doctores);
}
